#version 430 core
#extension GL_ARB_bindless_texture : require

const uint VIEW_PERSPECTIVE = 0u;
const uint VIEW_ORTHO		= 1u;

uniform uint clusterCount;
uniform uint viewIndexCount;
uniform uint clustersPerView;

layout(binding = 0, std430) readonly buffer IndexBuffer
{
	uint indices[];
};

struct IndirectMeshDraw
{
	uint count;
	uint first;
};
layout (binding = 1, std430) buffer IndirectMeshDrawBuffer
{
	IndirectMeshDraw indirectMeshDraws[];
};

struct Cluster
{
	vec4 boundingSphere;

	uint transformIndex;
	int materialIndex;

	uint indexCount;
	uint firstIndex;
	int vertexOffset;

	uint viewId;

	int padding1;
	int padding2;
};
layout (binding = 2, std430) readonly buffer ClusterBuffer
{
	Cluster clusters[];
};

layout (binding = 3, std430) buffer ClusterBatchBuffer
{
	uint writeClusters[];
};

struct Material
{
	vec4 colorFactor;

	uvec2 baseColorTex;
	uvec2 metallicRoughnessTex;
	uvec2 normalTex;

	float metallicFactor;
	float roughnessFactor;

	bool hasColorTex;
	bool hasMetallicRoughnessTex;
	bool hasNormalTex;

	bool alphaMask;
	float alphaCutoff;
	bool alphaBlend;

	uvec2 padding;
};
layout (binding = 6, std430) readonly buffer MaterialBlock
{
	Material materials[];
};

layout(binding = 8, std430) readonly buffer TransformBuffer
{
	mat4 transforms[];
};

layout (binding = 9, std430) buffer VisibilityBitmask
{
	uint visibilityBitmask[];
};

struct Frustum
{
	vec4 top;
	vec4 bottom;

	vec4 right;
	vec4 left;

	vec4 far; // unused
	vec4 near;
};

struct View
{

	mat4 view;
	mat4 proj;

	Frustum frustum;

	vec4 camPosAndZNear;
	uvec2 hiZ;

	uint projType;

	float zFar;
};
layout (binding = 10, std430) readonly buffer ViewBuffer
{
	View views[];
};



float map(float value, float min1, float max1, float min2, float max2)
{
  return min2 + (value - min1) * (max2 - min2) / (max1 - min1);
}



// todo: parameter names
vec4 transformSphere(vec4 sphere, mat4 modelTransform, mat4 viewMatrix)
{
	vec3 scale;
	scale.x = length(vec3(modelTransform[0]));
	scale.y = length(vec3(modelTransform[1]));
	scale.z = length(vec3(modelTransform[2]));

	vec3 center = vec3(modelTransform * vec4(sphere.xyz, 1.0f));

	float maxScale = max(scale.x, max(scale.y, scale.z));

	center = vec3(viewMatrix * vec4(center, 1.0f));

	vec4 globalSphere = vec4(center, sphere.w * maxScale);

	return globalSphere;
}

float getSignedDistanceToPlane(vec4 plane, vec3 point)
{
	return dot(plane.xyz, point) + plane.w;
}

bool sphereIsOnOrForwardPlane(vec4 sphere, vec4 plane)
{
	return getSignedDistanceToPlane(plane, sphere.xyz) > -sphere.w;
}

bool sphereIsOnViewFrustum(vec4 sphere, mat4 transform, Frustum frustum)
{
	vec3 scale;
	scale.x = length(vec3(transform[0]));
	scale.y = length(vec3(transform[1]));
	scale.z = length(vec3(transform[2]));

	vec3 center = vec3(transform * vec4(sphere.xyz, 1.0f));

	float maxScale = max(scale.x, max(scale.y, scale.z));

	vec4 globalSphere = vec4(center, sphere.w * maxScale);

	return ((sphereIsOnOrForwardPlane(globalSphere, frustum.left)) &&
		(sphereIsOnOrForwardPlane(globalSphere, frustum.right)) &&
		(sphereIsOnOrForwardPlane(globalSphere, frustum.near)) &&
		(sphereIsOnOrForwardPlane(globalSphere, frustum.top)) &&
		(sphereIsOnOrForwardPlane(globalSphere, frustum.bottom)));
}

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
bool projectSphereView(vec3 c, float r, float znear, mat4 proj, uint projType, out vec4 aabb)
{
    if (c.z < r + znear) return false;

	if (projType == VIEW_PERSPECTIVE)
	{
		vec3 cr = c * r;
		float czr2 = c.z * c.z - r * r;

		float vx = sqrt(c.x * c.x + czr2);
		float minx = (vx * c.x - cr.z) / (vx * c.z + cr.x);
		float maxx = (vx * c.x + cr.z) / (vx * c.z - cr.x);

		float vy = sqrt(c.y * c.y + czr2);
		float miny = (vy * c.y - cr.z) / (vy * c.z + cr.y);
		float maxy = (vy * c.y + cr.z) / (vy * c.z - cr.y);

		aabb = vec4(minx * proj[0][0], miny * proj[1][1], maxx * proj[0][0], maxy * proj[1][1]);
	}
	else if (projType == VIEW_ORTHO)
	{
		vec4 minc = vec4(c - r, 1.0f);
		vec4 maxc = vec4(c + r, 1.0f);
		minc = proj * minc;
		maxc = proj * maxc;

		aabb = vec4(minc.xy, maxc.xy);
	}

    // clip space -> uv space
    aabb = aabb.xwzy * vec4(0.5f) + vec4(0.5f);

    return true;
}

float sampleHiZ(ivec2 coords, int level, uvec2 hiZ)
{
	if (textureSize(sampler2D(hiZ), 0).x != 1440)
	{
		return -1.0f;
	}

	if (coords.x < 0 || coords.y < 0) coords = ivec2(0, 0);

	if (coords.x >= textureSize(sampler2D(hiZ), level).x) coords.x = textureSize(sampler2D(hiZ), level).x -1;
	if (coords.y >= textureSize(sampler2D(hiZ), level).y) coords.y = textureSize(sampler2D(hiZ), level).y -1;

	return texelFetch(sampler2D(hiZ), ivec2(coords), level).x;
}



// Per cluster
layout (local_size_x = 1, local_size_y = 1, local_size_z = 64) in;
void main()
{
	uint clusterId = 
		gl_WorkGroupID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y +
		gl_WorkGroupID.y * gl_NumWorkGroups.x +
		gl_WorkGroupID.x;
	clusterId = clusterId * 64 + gl_LocalInvocationIndex;

	if (clusterId >= clusterCount)
	{
		return;
	}

	uint i = clusterId / 32;
	uint n = clusterId - i * 32;
	uint bits = 1 << n;
	bool clusterWasVisible = bool(visibilityBitmask[i] & bits);
	uint viewId = clusters[clusterId].viewId;

	bool isVisible = sphereIsOnViewFrustum(clusters[clusterId].boundingSphere,
		transforms[clusters[clusterId].transformIndex], views[viewId].frustum);

	mat4 viewMat        = views[viewId].view;
	mat4 proj           = views[viewId].proj;
	vec4 camPosAndZNear = views[viewId].camPosAndZNear;

	if (isVisible)
	{
		vec4 sphere = transformSphere(clusters[clusterId].boundingSphere, transforms[clusters[clusterId].transformIndex], viewMat);

		uint projType = views[viewId].projType;
		float zFar	  = views[viewId].zFar;

		float sphereProjZNear = projType == VIEW_ORTHO ? zFar : camPosAndZNear.w;

		vec4 aabb;
		if (projectSphereView(sphere.xyz * vec3(1.0f, 1.0f, -1.0f), sphere.w,
			sphereProjZNear, proj, projType, aabb))
		{
			uvec2 hiZ = views[viewId].hiZ;

			// aabb.xy is bottom left; aabb.zw is top right
			float width  = (aabb.z - aabb.x) * textureSize(sampler2D(hiZ), 0).x;
			float height = (aabb.w - aabb.y) * textureSize(sampler2D(hiZ), 0).y;

			int level = int(ceil(log2(max(width, height)))) + 1;
			level = min(level, textureQueryLevels(sampler2D(hiZ)) - 1);
			level = max(0, level);

			vec2 coords = floor(((aabb.xy + aabb.zw) * 0.5f) * vec2(textureSize(sampler2D(hiZ), level)));

			vec2 coords1 = ((aabb.xy + aabb.zw) * 0.5f) * vec2(textureSize(sampler2D(hiZ), level));
			coords1 = ceil(coords1);

			vec4 depths;
			depths.x = sampleHiZ(ivec2(coords),              level, hiZ);
			depths.y = sampleHiZ(ivec2(coords.x, coords1.y), level, hiZ);
			depths.z = sampleHiZ(ivec2(coords1),             level, hiZ);
			depths.w = sampleHiZ(ivec2(coords1.x, coords.y), level, hiZ);
			float depth = min(min(depths.x, depths.y), min(depths.z, depths.w));

			float sphereDepth = -abs(sphere.z) + abs(sphere.w);
			if (projType == VIEW_PERSPECTIVE)
			{
				sphereDepth = camPosAndZNear.w / -sphereDepth;
			}
			else if (projType == VIEW_ORTHO)
			{
				sphereDepth = map(sphereDepth, zFar, camPosAndZNear.w, 0.0f, 1.0f);
			}

			isVisible = sphereDepth >= depth;
		}
	}
	
	if (clusterWasVisible != isVisible)
	{
		if (isVisible)
		{
			atomicOr(visibilityBitmask[i], bits);
		}
		else
		{
			bits = ~bits;
			atomicAnd(visibilityBitmask[i], bits);

			return;
		}
	}
	if (!isVisible) return;

	//uint indexCount = clusters[clusterId].indexCount;

	// If cluster wasn't visible last frame, or cluster is alpha blend, batch it here
	if (materials[clusters[clusterId].materialIndex].alphaBlend)
	{
	/*
		uint bufferStart = viewId * viewIndexCount + atomicAdd(indirectBlendDraws[viewId].count, indexCount);

		for (int i = 0; i < indexCount; i++)
		{
			// 25 bits for cluster id, 7 bits for index
			uint index = (clusterId << 7) | indices[clusters[clusterId].firstIndex + i];
			writeBlendIndices[bufferStart + i] = index;
		}
		*/
	}
	else
	{
		if (!clusterWasVisible)
		{
			uint index = viewId * clustersPerView + atomicAdd(indirectMeshDraws[viewId].count, 1);
			writeClusters[index] = clusterId;
		}
	}
}