#version 430 core

uniform uint clusterCount;
uniform uint viewIndexCount; // likely unused, todo: delete
uniform uint clustersPerView;

// todo: unused?
layout(binding = 0, std430) readonly buffer IndexBuffer
{
	uint indices[];
};

struct IndirectMeshDraw
{
	uint count;
	uint first;
};
layout (binding = 1, std430) buffer IndirectMeshDrawBuffer
{
	IndirectMeshDraw indirectMeshDraws[];
};

struct Cluster
{
	vec4 boundingSphere;

	uint transformIndex;
	int materialIndex;

	uint indexCount;
	uint firstIndex;
	int vertexOffset;

	uint viewId;

	int padding1;
	int padding2;
};
layout (binding = 2, std430) readonly buffer ClusterBuffer
{
	Cluster clusters[];
};

layout (binding = 3, std430) buffer ClusterBatchBuffer
{
	uint writeClusters[];
};

struct Material
{
	vec4 colorFactor;

	uvec2 baseColorTex;
	uvec2 metallicRoughnessTex;
	uvec2 normalTex;

	float metallicFactor;
	float roughnessFactor;

	bool hasColorTex;
	bool hasMetallicRoughnessTex;
	bool hasNormalTex;

	bool alphaMask;
	float alphaCutoff;
	bool alphaBlend;

	uvec2 padding;
};
layout (binding = 6, std430) readonly buffer MaterialBlock
{
	Material materials[];
};

layout (binding = 9, std430) buffer VisibilityBitmask
{
	uint visibilityBitmask[];
};



// per cluster (clusters are meshlet instances)
layout (local_size_x = 4, local_size_y = 4, local_size_z = 4) in;
void main()
{
	uint clusterId = 
		gl_WorkGroupID.z * gl_NumWorkGroups.x * gl_NumWorkGroups.y +
		gl_WorkGroupID.y * gl_NumWorkGroups.x +
		gl_WorkGroupID.x;
	clusterId = clusterId * 64 + gl_LocalInvocationIndex;

	bool activeThread = clusterId < clusterCount;

	// test clusters against visibility bitmask. If they weren't visible last frame, they aren't occluders, and won't be batched.
	uint i = clusterId / 32;
	uint n = clusterId - i * 32;
	uint bits = 1 << n;
	bool clusterWasVisible = bool(visibilityBitmask[i] & bits);

	activeThread = activeThread && clusterWasVisible && !materials[clusters[clusterId].materialIndex].alphaBlend;

	if (activeThread)
	{
		uint viewId = clusters[clusterId].viewId;

		uint index = viewId * clustersPerView + atomicAdd(indirectMeshDraws[viewId].count, 1);
		writeClusters[index] = clusterId;
	}

}